apiVersion: v1
stringData:
  support-bundle-spec: |
{{- include "support-bundle.spec" . | indent 4 }}
kind: Secret
metadata:
  labels:
    troubleshoot.io/kind: support-bundle
  name: {{ .Release.Name }}-support-bundle
  namespace: {{ .Release.Namespace }}
type: Opaque